version: '3'

services:
  node:
    container_name: node
    build: ./app
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
      - ./app:/usr/src/app
    ports:
      - ${APP_PORT:-8080}:8080
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
  front:
    container_name: front-dev
    build:
      context: ./front
      dockerfile: Dockerfile
    image: knbase-front-dev
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
      - ./front:/app
    ports:
      - ${APP_FRONT_PORT:-5173}:5173
    tty: true
volumes:
  mongodb:
    driver: local